tasks/main.yml
cc: 
The ansible wait_for module checks to ensure a TCP connection can be made. This results in this role failing to complete on first iteration with the following error:
```
failed: [jenkinstest] => {"attempts": 5, "dest": "/opt/jenkins-cli.jar", "failed": true, "response": "HTTP Error 503: Service Unavailable", "state": "absent", "status_code": 503, "url": "http://localhost:8080/jnlpJars/jenkins-cli.jar"}
msg: Task failed as maximum retries was encountered
```
Switch to checking the response code of Jenkins.
This addresses GitHub Issue: https://github.com/geerlingguy/ansible-role-jenkins/issues/12
=> Update wait to use curl instead of wait_for since Jenkins is Java

README.md, defaults/main.yml, tasks/main.yml
cc: 
My vagrant still failed to provision due to Jenkins throwing a 503 after 60 seconds. Let's use the same validation but allow consumers of this role to configure how long they're willing to wait.
:cry: 
Extrapolate out the hard-coded timeout and retries to be variables.
=> Enable the duration of the retries to be configurable

README.md, tasks/main.yml, tasks/plugins.yml, tasks/setup-Debian.yml, tasks/setup-RedHat.yml
Sometimes it is desirable to put Jenkins behind a reverse proxy, which most likely requires a path prefix in the URL, e.g. http://www.example.com/ci/.
We can achieve this by parsing the "--prefix" argument in the invocation of Jenkins in /etc/default/jenkins.
=> Allow hosting with a path prefix, e.g. /ci

tasks/main.yml
The fact that the http port is open is not complete indication of Jenkins restart.
It can happen sometimes that Jenkins needs more time to start completely.
Thank you.
=> Correclty ensure that jenkins has started.

README.md
- Add missing closing backtick which was causing the rest of the
sentence to be rendered as code.
- Remove superfluous slash in example. The jenkins_url_prefix is
expected to begin with a slash, so it's not necessary to put
one before its usage.
Change-Id: I0a56296b714d8ec3e83aa03fad1ccfe864da337c
=> README: Fix formatting in description of jenkins_url_prefix

tasks/main.yml
A secured Jenkins changes its HTTP status from "200 OK: Please wait while ..." to "403 Forbidden" when it starts (and not to "200 OK" like an unsecured Jenkins).
Without this commit the role hangs if Jenkins' security has been enabled after the initial installation. Other than that, the role works fine with a secured Jenkins as long as the Unix user's public key has been added to a Jenkins user with administrator permissions.
=> Fix waiting for startup when security is enabled

.travis.yml, README.md, defaults/main.yml, tasks/main.yml, tasks/plugins.yml, tasks/settings.yml, tests/test-http-port.yml, vars/Debian.yml, vars/RedHat.yml
The HTTP port is configurable with the 'jenkins_http_port' variable.
For Debian/Ubuntu, the configuration variable HTTP_PORT is used.
For RedHat/CentOS, the configuration variable JENKINS_PORT is used.
The default port value is 8080.
Change-Id: I6f2a8e027e8a2a04186b0a26789ffb524f5ac58a
=> Fixes #23: Allow to configure the HTTP port

tasks/settings.yml
Add a 'regexp' line to the URL prefixing so that we don't
insert multiple lines for defining --prefix when we change
jenkins_url_prefix.
=> Fixes: #33: Support changes to jenkins_url_prefix

tasks/prefix.yml
Causes an exception of:
```
/var/lib/dpkg/info/jenkins.postinst: 76: /etc/default/jenkins: JENKINS_ARGS+= --prefix=: not found
dpkg: error processing package jenkins (--configure):
subprocess installed post-installation script returned error exit status 127
```
Figured I'd just go and fix it.
=> Issues when upgrading package via apt-get

tasks/settings.yml
Jenkins 2.0 introduces an interactive Setup Wizard which breaks
automatic configuration. The Setup Wizard needs to be disabled before
Jenkins is starting for the first time.
=> Disable Jenkins 2.0 Setup Wizard

tests/Dockerfile.centos-6, tests/Dockerfile.centos-7, tests/Dockerfile.ubuntu-12.04, tests/Dockerfile.ubuntu-14.04
I rewrite following the layer rule, one RUN, one action.
For **Debian/Ubuntu**,  I add clean-up below:
```
&& rm -rf /var/lib/apt/lists/* \
&& rm -Rf /usr/share/doc && rm -Rf /usr/share/man \
&& apt-get clean
```
For **Centos**, I have just "align" install and clean: 
```
RUN yum -y install <packages>; yum clean all
```
**Before**
```
REPOSITORY                     TAG                 IMAGE ID            SIZE
centos-7                       ansible             d6679028c8d8        477.7 MB
centos-6                       ansible             c5044c62f0e6        412.3 MB
ubuntu-14.04                   ansible             21c4c03a0711        347.2 MB
ubuntu-12.04                   ansible             4942aa95bdc8        327.1 MB
```
**After**
```
REPOSITORY                     TAG …
```
=> Dockerfile improvement: Lighter (~20%)

README.md, defaults/main.yml, tasks/settings.yml
Opening this to address the issue https://github.com/geerlingguy/ansible-role-jenkins/issues/66
=> Use the var jenkins_java_options to set extra Java options in the init file

tasks/settings.yml, tasks/setup-Debian.yml, tasks/setup-RedHat.yml
When jenkins install is called, both tasks are visited. And
it registers result of jenkins_install_package twice, causing
it to have a wrong value, and don't install jenkins users, causing
security to don't be configure and plugins to fail.
It's better to add different vars for each task, and trigger
the users install in case of some of the two changed.
=> Register independent vars on each install type

README.md, defaults/main.yml, tasks/plugins.yml
I suggest to add the possibility to use the password file as an argument of the jenkins-cli.
So I add a condition on the install-plugin task in order to apply with password or with password-file.
If the password and the password-file are both set, that's trigger twice the plugins installation. That's a bit ugly but the user have to choose.
=> Plugins: Add password-file.

README.md, defaults/main.yml, tasks/main.yml, tasks/plugins.yml, tasks/settings.yml
Added support for specifying the Jenkins home directory. This allows users to store their artefacts in a preferred location.
The previously used ‘/var/lib/jenkins’ directory is used as the default value. All hardcoded path references have been updated to use the newly introduced {{ jenkins_home }} variable.
=> Jenkins Home Directory Support

.travis.yml, README.md, defaults/main.yml, tasks/setup-Debian.yml, tests/Dockerfile.centos-7, vars/Debian.yml, vars/RedHat.yml
I was getting the following error on CentOS 7:
```
TASK [role_under_test : Immediately restart Jenkins on init config changes.] ***
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Job for jenkins.service failed because the control process exited with error code. See \"systemctl status jenkins.service\" and \"journalctl -xe\" for details.\n"}
[ERROR]: Could not create retry file '/etc/ansible/roles/role_under_test/tests
/test-jenkins-version.retry'. The error was: [Errno 30] Read-only file system:
'/etc/ansible/roles/role_under_test/tests/test-jenkins-version.retry'
```
After doing some digging (debugging with `systemctl -l status jenkins.service` and `journalctl -xe --no-pager`), I found that the true error was:
```
Aug 10 05:06:32 d0e401af0f09 systemd[1]: …
```
=> Jenkins tweaks and CentOS 7 install

.travis.yml, handlers/main.yml, tasks/plugins.yml, tasks/settings.yml, tasks/setup-Debian.yml, tasks/setup-RedHat.yml, tests/test-plugins-with-pinning.yml
When we added the ability to pin versions, it broke the ability to install
plugins since it doesn't register the variables correctly to trigger the
changes introduced in #72.
Unfortunately, the fix of adding a register to the pinned version package
installation module (yum / apt) execution re-introduces the exact same issue
that #72 is attempting to resolve.
So, in order to work around that limitation, I've moved the deployment of
the authentication groovy script to a handler, and then notified that handler
from both the application installation routines.
There is also the addition of a meta module to flush the handlers so that
the groovy script is installed immediately, and thereby registering the
correct values to trigger a restart of Jenkins if necessary.
Resolves #70
=> Allow plugin install to work using pinned versions

README.md, defaults/main.yml, vars/Debian.yml
Default __jenkins_pkg_url in vars/Debian.yml contained trailing slash which resulted in URLS like `https://pkg.jenkins.io/debian-stable//jenkins_X.X_all.deb`. vars/RedHat.yml is OK though. Also removed the slash in the examples.
=> Trailing slash removed from jenkins_pkg_url

tasks/main.yml
Two tasks failed when the role was run in Check Mode (with --check). The needed opt-out parameter `check_mode` is only available in Ansible 2.2, thus the min version bump.
This is an alternative for #102 and fixes #96.
Would be great if merged and released - what's your opinion?
=> Add Check Mode support.

README.md, defaults/main.yml, tasks/plugins.yml, tests/test-plugins.yml
I found that it takes more than 30 secs for some plugins to be installed, so that's the purpose of this pull: allow configuring the timeout using a predefined variable
=> Support overriding timeout when installing plugins

defaults/main.yml, handlers/main.yml, tasks/settings.yml
I was getting a permission denied error when Jenkins was trying to start and read `basic-security.groovy`, because the file was owned by `root`. This change makes the file ownership explicit.
=> set the owner of the basic-security script

tasks/settings.yml
This is needed when custom path is used, as correct owner/group cannot
be set before jenkins package (and jenkins user creation) is done.
It is difficult to handle elsewhere than in your role as it is not possible to assign the right ownership and permission before jenkins is installed. I use a minimalist behavior on permission setting, with just owner permission check (u+rwx).
=> Ensure that jenkins_home exists

tasks/setup-Debian.yml, tasks/setup-RedHat.yml
Fix for day 2 upgrades on Jenkins.
The get_url module by default does not download the file from the source URL if it already exists on the system. This does not mean it does'nt download the file from the URL if it's the "same" as the one system, but rather it will not download the file if a file with the same name already exists - I detect no consideration for the contents or hash of the source and dest files. This causes an issue when you already have Jenkins installed using the module and decide to bump up the version. In my case this was from 2.32.2 to 2.46.1. But the role executed without any changes. The cause was the get_url module and how it works: http://docs.ansible.com/ansible/get_url_module.html
My updates provide a way to resolve this situation while maintaining idempotency …
=> Fix day 2 Jenkins upgrades

README.md, defaults/main.yml, tasks/plugins.yml
Once the jenkins master is installed, we often connect it to an LDAP server.
In my case the admin account is not defined in the LDAP for some security reasons.
Before connect the Jenkins master to the LDAP, I can retrieve the admin token, connect Jenkins to the LDAP and use the token to update the plugins.
And so, if I want to continue to manage my plugins updates with this role, I need a such enhancement.
So I suggest to create jenkins_admin_token and jenkins_admin_token_file to use the `url_token` params of `jenkins_plugins`.
By the way, commit https://github.com/olo-dw/ansible-role-jenkins/commit/2bc26e0d2ffdf7a357b0c09ab7001efe07dc6b13 improves the idempotence using the slurp module instead of command
=> Plugins token

.travis.yml, tasks/plugins.yml, tests/test-plugins-with-home.yml
If you set jenkins_home and install any plugin, then the overridden variable is not applied to the jenkins_plugin Ansible module, so the plugin tries to be installed in `/var/lib/jenkins` instead of the new path
=> Honor jenkins_home variable from jenkins_plugin module

README.md, tasks/setup-Debian.yml, tasks/setup-RedHat.yml
A small change to allow a user to disable the repo fetching task in the setup playbooks. 
For systems that sign their own RPMs / DEBs - this stops the role from running.
=> option to disable repo download

tasks/plugins.yml
* Update plugin database before installing Jenkins plugins (eliminates build failures).  See the following for additional information - 
- http://www.mymiller.name/wordpress/app/1515/
- https://www.jeffgeerling.com/blog/2017/ansible-jenkinsplugin-module-and-404-plugin-not-found
=> Plugin Database Update

tasks/plugins.yml
The params argument has been deprecated. We can pass the params as bare
args to the task instead.
Fixes #199.
=> Stop using the params argument to jenkins_plugin

README.md, defaults/main.yml, tasks/plugins.yml
I wanted to install the pipeline plugin and needed all it's dependencies installed too. I thought that it made sense to install plugins and their dependencies in general.
=> Install plugins with dependencies by default

tasks/settings.yml
On constrained space one might move /var/lib/jenkins elsewhere and keep
the old location as a symlink. So follow that instead of failing.
=> Allow jenkins_home to be a symlink

README.md, defaults/main.yml, tasks/plugins.yml
Added this variable and set it to "https://updates.jenkins.io" since, the default one in outdated.
=> Added jenkins_updates_url variable

tasks/plugins.yml
Sometimes the plugin downloads can timeout for myriad reasons. plus, it is "linty" to have retries on anything that fetches external files
=> added retries to the get_url and jenkins_plug tasks

tasks/setup-Debian.yml
Hi,
testing on Ubuntu 18.04, I realized that gnupg is needed for ansible's apt_key module to work as expected.
Nice role by the way!
=> gnupg is needed on Ubuntu to add Jenkins apt repository key

tasks/setup-RedHat.yml
If you elect to not install the repo, trying to install the GPG key is a waste, and worse, in environments where you skip the repo because you wish to directly download from an HTTP mirror, trying to install the (blocked off internet) gpg key location will fail the play.
=> Skip GPG key when not installing the repo

README.md
`geerlingguy.java` is applied twice if `java_packages` parameter is passed.
And `geerlingguy.jenkins` works without explicit specification of `geerlingguy.java`.
`geerlingguy.java` should be removed from the example playbook.
playbook.yml
```yaml
- hosts: jenkins
vars:
jenkins_hostname: jenkins.example.com
roles:
- role: geerlingguy.java
become: yes
java_packages:
- openjdk-8-jdk
- role: geerlingguy.jenkins
become: yes
```
result:
```
...
TASK [geerlingguy.java : Ensure Java is installed.] *********************************************************************************************************************************
ok: [192.168.33.10] => (item=[u'openjdk-8-jdk'])
...
TASK [geerlingguy.java : Ensure Java is installed.] ********************************************************************** …
```
=> fix example playbook

defaults/main.yml, tasks/settings.yml, templates/proxy.xml
Jenkins breaks when it sits behind a proxy unconfigured.
In our particular use case plugins will not install correctly.
This PR adds parameters/config to allow a proxy to be configured.
This was previously raised by a colleague in PR207
https://github.com/geerlingguy/ansible-role-jenkins/pull/207
=> Add unauthenticated proxy options.

README.md, meta/main.yml
Fixes #195. There's no way to maintain compatibility, but I updated the documentation. Semantically, this change my justify a bump in the major version number.
=> Remove strict dependency on geerlingguy.java role

README.md, defaults/main.yml, vars/Debian.yml, vars/RedHat.yml
It's convenient to be able to prefer LTS over weekly releases without having to set two variables to platform-specific values in inventories or playbooks.
=> Add jenkins_prefer_lts variable

tasks/setup-RedHat.yml
Hi @geerlingguy,
I need to use the module to manage jenkins on different servers.  Some have python 2, others have python 3.
I know that ansible are trying to remove the requirement for libselinux, but until then, we need to cope with both.
Please can this be merged.
Thanks,
Neil
=> #283: Install correct libselinux RPM for the python version

tasks/setup-Debian.yml
When installing with the role on Ubuntu we are seeing:
```
W: https://pkg.jenkins.io/debian/binary/Release.gpg: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
```
As far as I could tell, this is the recommended replacement and should be supported for quite some time now.
=> Replace deprecated apt_key usage

vars/Debian.yml
This pull request addresses issue [#378](https://github.com/geerlingguy/ansible-role-jenkins/issues/378) . The purpose of this update is to ensure compatibility with Jenkins' new repository signing keys.
Jenkins has recently made changes to its signing keys. As a result, requests that do not utilize these new keys are being blocked. To maintain the functionality and security of the Jenkins role it is necessary to update the signing keys used within the code.
For more information please refer to the following link: [Jenkins Blog - Repository Signing Keys Changing](https://www.jenkins.io/blog/2023/03/27/repository-signing-keys-changing/)
Thank you for considering this pull request.
=> fix: Use new Debian repository signing keys

README.md
Current status badge is shown as "failing" although latest CI run has passed. 
Reference: https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge#using-the-workflow-file-name.
=> Fix CI status badge link

README.md, defaults/main.yml, handlers/main.yml, tasks/restart.yml
Hi @geerlingguy 🙂,
as I described here #390, I want to update my Jenkins server itself. With this variable I can run the Jenkins CLI with `safe-restart` and everything is fine.
=> Add `jenkins_restart_method` to allow a `safe restart` to be performed.
